# Generated by Django 5.0.2 on 2024-03-02 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='portfolios',
            field=models.ManyToManyField(related_name='projects_associated', through='portfolio_app.ProjectInPortfolio', to='portfolio_app.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.ManyToManyField(related_name='portfolios_associated', through='portfolio_app.ProjectInPortfolio', to='portfolio_app.project'),
        ),
    ]
