# Generated by Django 5.0.2 on 2024-03-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_projectinportfolio_project_portfolios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='portfolios',
        ),
        migrations.DeleteModel(
            name='ProjectInPortfolio',
        ),
    ]
